title: her.sh
url: https://her.sh
blog: http://list.her.sh

sandbox:
  url: https://z.her.sh

splinesoft:
  url: http://splinesoft.net
  github: https://github.com/splinesoft

mudurl: https://itunes.apple.com/us/app/mudrammer-a-modern-mud-client/id597157072?mt=8
mudsource: https://github.com/splinesoft/MUDRammer
bequesturl: https://github.com/splinesoft/bequest
ciurl: https://circleci.com/gh/jhersh/her.sh

exclude: [.bundle, .git, Gemfile, Gemfile.lock, readme.md, Rakefile, vendor, circle.yml, s3cmd-1.5.2]

author:
  name: Jonathan Hersh
  email: jon@her.sh
  github: https://github.com/jhersh
  linkedin: https://www.linkedin.com/in/jhersh
  pgp: https://her.sh/pgp.txt
  source: https://github.com/jhersh/her.sh
  keybase: https://keybase.io/zz
